// Define schema
const mongoose=require('mongoose');
var uniqueValidator = require('mongoose-unique-validator');
var Schema = mongoose.Schema;
var PatientSchema = new Schema({
    claveMexpharm:String,
	claveInst:{ type: String, required: true, unique: false },
	codigoVerificador:{ type: String, required: true, unique: true },
	anyo:String,
	mes:String,
	dia:String,
	medicoResponsable:String,
	medicoTratante:String,
	nombre:String,
	sexo:String,
	edad:String,
	rEdad:String,
	edoCivil:String,
	otroEdoCivil:String,
	viveCon:String,
	otroViveCon:String,
	viveCuantos:String,
	viviendaEs:String,
	ingresoMensual:String,
	nPersonasAportan:String,
	localidad:String,
	claveMunicipio:String,
	municipio:String,
	claveEFederativa:String,
	eFederativa:String,
	lugarNacimiento:String,
	ocupacion:String,
	actRemunerada:String,
	actRemuneradaCual:String,
	clacificacionOjo:String,
	intervencionOjoD:String,
	intervencionOjoI:String,
	procedimiento:String,
	observaciones:String,
	complicacione:String,
	sedeCamp:String,
	insumos:String,
	folioConsignia:String,
	actAntesDeCirugia:String,
	nActAntesDeCirugia:String,
	oActAntesDeCirugia:String,
	actDespuesDeCirugia:String,
	nActDespuesDeCirugia:String,
	oActDespuesDeCirugia:String,
	telefono:String,
	satisfaccion:String,
});
module.exports = mongoose.model('Patient', PatientSchema );